/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * actionListFrame.java
 *
 * Created on 28.11.2010, 02:30:59
 */
package schoolalyzer;

import schoolalyzer.util.Tuple;
import java.util.LinkedList;
import java.util.Map;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import schoolalyzer.actions.AbstractCellAction;

/**
 *
 * @author uli
 */
public class ActionListFrame extends javax.swing.JFrame {

    private SchoolalyzerFrame parentFrame = null;

    /** Creates new form actionListFrame */
    public ActionListFrame() {
        initComponents();
        tree.setModel(getModel());
    }

    public void setParentFrame(SchoolalyzerFrame parentFrame) {
        this.parentFrame = parentFrame;
    }

    private DefaultTreeModel getModel() {
        DataMutableTreeNode rootNode = new DataMutableTreeNode("Blätter");
        for (Map.Entry<String, LinkedList<AbstractCellAction>> entry : parentFrame.getActions().entrySet()) {
            DataMutableTreeNode sheetNode = new DataMutableTreeNode(entry.getKey());
            sheetNode.setType("sheet");
            for (AbstractCellAction action : entry.getValue()) {
                DataMutableTreeNode actionNode = new DataMutableTreeNode(action.getActionName());
                actionNode.setType("action");
                actionNode.setData(new Tuple<String, AbstractCellAction>(entry.getKey(), action));
                sheetNode.add(actionNode);
            }
        }
        return new DefaultTreeModel(rootNode);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        treeScrollPane = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Schoolalyzer - Berechnungen");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        treeScrollPane.setViewportView(tree);

        getContentPane().add(treeScrollPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree tree;
    private javax.swing.JScrollPane treeScrollPane;
    // End of variables declaration//GEN-END:variables
}
