/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CSVImporterFrame.java
 *
 * Created on 02.12.2010, 20:21:45
 */
package schoolalyzer;

import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import schoolalyzer.util.POIUtil;

/**
 *
 * @author uli
 */
public class CSVImporterFrame extends javax.swing.JFrame {
    //File choosers

    private JFileChooser outputChooser = new JFileChooser();
    private JFileChooser templateChooser = new JFileChooser();
    private JFileChooser inputFileChooser = new JFileChooser();
    //Logging
    private static final Logger logger = Logger.getLogger(CSVImporterFrame.class.getName());
    //Status variables
    boolean templateSet = false;
    boolean inputsSet = false;
    boolean outputSet = false;
    //IO data
    private List<File> inputFiles = null;
    private Workbook outputWorkbook = null;
    private File outputWorkbookFile = null;

    /** Creates new form CSVImporterFrame */
    public CSVImporterFrame() {
        initComponents();
    }

    /**
     * Saves the output workbook in the output file
     */
    private void saveOutputWorkbook() throws IOException {
        OutputStream os = new BufferedOutputStream(new FileOutputStream(outputWorkbookFile));
        outputWorkbook.write(os);
        os.close();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        templateFileLabel = new javax.swing.JLabel();
        selectTemplateButton = new javax.swing.JButton();
        templateStatusLabel = new javax.swing.JLabel();
        inputStatusLabel = new javax.swing.JLabel();
        selectInputFilesButton = new javax.swing.JButton();
        inputFilesLabel = new javax.swing.JLabel();
        outputFileLabel = new javax.swing.JLabel();
        selectOutputFileButton = new javax.swing.JButton();
        outputStatusLabel = new javax.swing.JLabel();
        applyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        templateFileLabel.setText("Vorlage:");

        selectTemplateButton.setText("Auswählen");
        selectTemplateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTemplateButtonActionPerformed(evt);
            }
        });

        templateStatusLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolalyzer/icons/dialog-information.png"))); // NOI18N
        templateStatusLabel.setText("Bitte Vorlage laden!");

        inputStatusLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolalyzer/icons/dialog-information.png"))); // NOI18N
        inputStatusLabel.setText("Bitte Eingabedateien laden!");

        selectInputFilesButton.setText("Auswählen");
        selectInputFilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectInputFilesButtonActionPerformed(evt);
            }
        });

        inputFilesLabel.setText("Eingabedateien:");

        outputFileLabel.setText("Ausgabedatei:");

        selectOutputFileButton.setText("Auswählen");
        selectOutputFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectOutputFileButtonActionPerformed(evt);
            }
        });

        outputStatusLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolalyzer/icons/dialog-information.png"))); // NOI18N
        outputStatusLabel.setText("Bitte Ausgabedatei auswählen !");

        applyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolalyzer/icons/task-complete.png"))); // NOI18N
        applyButton.setText("Anwenden");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(templateFileLabel)
                            .addGap(69, 69, 69)
                            .addComponent(selectTemplateButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(templateStatusLabel))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inputFilesLabel)
                                .addComponent(outputFileLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(selectOutputFileButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(outputStatusLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(selectInputFilesButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(inputStatusLabel)))))
                    .addComponent(applyButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(templateFileLabel)
                    .addComponent(selectTemplateButton)
                    .addComponent(templateStatusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputFilesLabel)
                            .addComponent(selectInputFilesButton)
                            .addComponent(inputStatusLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(outputFileLabel)
                            .addComponent(selectOutputFileButton)))
                    .addComponent(outputStatusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectTemplateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTemplateButtonActionPerformed
        //Show a dialog
        templateChooser.setDialogTitle("Vorlage auswählen");
        templateChooser.setMultiSelectionEnabled(false);
        if (templateChooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }
        File templateFile = templateChooser.getSelectedFile();
        //If the action does not succeed, the users sees the standard message
        templateSet = false;
        templateStatusLabel.setText("Bitte Vorlage laden!");
        templateStatusLabel.setIcon(SchoolalyzerFrame.informationIcon);
        //Load the template
        try {
            outputWorkbook = POIUtil.loadWorkbook(templateFile); //There is no separate templateWorkbook variable because the only use of the template file is to provide empty fields for the output
            templateStatusLabel.setIcon(SchoolalyzerFrame.okIcon);
            templateStatusLabel.setText("Vorlage erfolgreich geladen");
            templateSet = true;
        } catch (IOException ex) {
            templateStatusLabel.setIcon(SchoolalyzerFrame.errorIcon);
            templateStatusLabel.setText("Eingabefehler - bitte Vorlage erneut laden!");
        } catch (InvalidFormatException ex) {
            JOptionPane.showMessageDialog(this, "Fehler beim Lesen der Vorlage: Das Dateiformat wird nicht unterstützt: " + ex.getLocalizedMessage(), "Format nicht unterstützt", JOptionPane.ERROR_MESSAGE, SchoolalyzerFrame.errorIcon);
            templateStatusLabel.setIcon(SchoolalyzerFrame.errorIcon);
            templateStatusLabel.setText("Formatfehler - bitte Vorlage erneut laden!");
        }
}//GEN-LAST:event_selectTemplateButtonActionPerformed

    private void selectInputFilesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectInputFilesButtonActionPerformed
        //Let the user select the files to load
        inputFileChooser.setDialogTitle("Eingabedateien auswählen");
        inputFileChooser.setMultiSelectionEnabled(true);
        if (inputFileChooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }
        File[] dataFiles = inputFileChooser.getSelectedFiles();
        if (dataFiles.length == 0) {
            return; //No files to be processed
        }
        //Reset the input workbook data
        inputFiles.clear();
        inputFiles.addAll(Arrays.asList(dataFiles));
        //Set the status message
        inputsSet = true;
        inputStatusLabel.setIcon(SchoolalyzerFrame.okIcon);
        inputStatusLabel.setText(inputFiles.size() + " Eingabedateien erfolgreich geladen");
}//GEN-LAST:event_selectInputFilesButtonActionPerformed

    private void selectOutputFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectOutputFileButtonActionPerformed
        outputChooser.setDialogTitle("Select the output file");
        if (outputChooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }
        outputSet = false;
        File tempOutputFile = outputChooser.getSelectedFile();
        if (tempOutputFile.exists()) {
            int overwrite = JOptionPane.showConfirmDialog(this, "Datei existiert - überschreiben?", "Überschreiben", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (overwrite != JOptionPane.YES_OPTION) {
                return;
            }
        }
        if (!tempOutputFile.canWrite() && (!tempOutputFile.exists() && !tempOutputFile.getParentFile().canWrite())) {
            JOptionPane.showMessageDialog(this, "In diese Datei kann nicht geschrieben werden! Bitte andere Ausgabedatei wählen!", "Schreiben nicht erlaubt", JOptionPane.ERROR_MESSAGE, SchoolalyzerFrame.errorIcon);
            return;
        }
        //Everything's OK, so set the status label and the output file member variable
        outputWorkbookFile = tempOutputFile;
        outputStatusLabel.setIcon(SchoolalyzerFrame.okIcon);
        outputStatusLabel.setText("Ausgabedatei erfolgreich gesetzt");
        outputSet = true;
}//GEN-LAST:event_selectOutputFileButtonActionPerformed

    private void handleCSVFile(String name, InputStream in)
    {
        //Get the sheet or create it if it doesn't exist
        Sheet sheet = outputWorkbook.getSheet(name);
        if(sheet == null)
        {

        }
    }

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        for(File inputFile : inputFiles)
        {

        }
        try {
            //Save the output workbook
            saveOutputWorkbook();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Fehler beim Schreiben des Dokuments: " + ex.getLocalizedMessage(), "Schreibfehler", JOptionPane.ERROR_MESSAGE, SchoolalyzerFrame.errorIcon);
        }
        JOptionPane.showMessageDialog(this, "Die Berechnung wurde erfolgreich abgeschlossen!", "Erfolg", JOptionPane.INFORMATION_MESSAGE, SchoolalyzerFrame.okIcon);
}//GEN-LAST:event_applyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CSVImporterFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JLabel inputFilesLabel;
    private javax.swing.JLabel inputStatusLabel;
    private javax.swing.JLabel outputFileLabel;
    private javax.swing.JLabel outputStatusLabel;
    private javax.swing.JButton selectInputFilesButton;
    private javax.swing.JButton selectOutputFileButton;
    private javax.swing.JButton selectTemplateButton;
    private javax.swing.JLabel templateFileLabel;
    private javax.swing.JLabel templateStatusLabel;
    // End of variables declaration//GEN-END:variables
}
