/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExcelTablePanel.java
 *
 * Created on 26.11.2010, 20:34:52
 */

package schoolalyzer;

import org.apache.poi.ss.usermodel.Sheet;

/**
 *
 * @author uli
 */
public class ExcelTablePanel extends javax.swing.JPanel {
    private Sheet sheet = null;

    /** Creates new form ExcelTablePanel */
    public ExcelTablePanel() {
        initComponents();
    }

    public void setSheet(Sheet sheet) {
        this.sheet = sheet;
        table.setDefaultRenderer(Object.class, new ExcelCellRenderer(sheet));
        table.setModel(new ExcelTableModel(sheet));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableScrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScrollPane.setViewportView(table);

        add(tableScrollPane);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables

}
