/*
 * SchoolalzyerFrame.java
 *
 * Created on 26.11.2010, 20:27:52
 */
package schoolalyzer;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;

/**
 *
 * @author uli
 */
public class SchoolalzyerFrame extends javax.swing.JFrame {

    private Workbook templateWorkbook = null;
    private ArrayList<Workbook> inputWorkbooks = null;
    private Workbook outputWorkbook = null;
    private File outputWorkbookFile = null;
    private ImageIcon infoIcon = new ImageIcon(getClass().getResource("/schoolalyzer/icons/dialog-information.png"));
    private ImageIcon warningIcon = new ImageIcon(getClass().getResource("/schoolalyzer/icons/dialog-warning.png"));
    private ImageIcon errorIcon = new ImageIcon(getClass().getResource("/schoolalyzer/icons/dialog-error.png"));
    private ImageIcon okIcon = new ImageIcon(getClass().getResource("/schoolalyzer/icons/task-complete.png"));

    private Workbook loadWorkbook(File file) throws IOException, InvalidFormatException {
        InputStream in = new BufferedInputStream(new FileInputStream(file));
        Workbook workbook = WorkbookFactory.create(in);
        in.close();
        return workbook;
    }

    /**
     * Saves the output workbook in the output file
     */
    private void saveOutputWorkbook() throws IOException {
        OutputStream os = new BufferedOutputStream(new FileOutputStream(outputWorkbookFile));
        outputWorkbook.write(os);
        os.close();
    }

    /** Creates new form SchoolalzyerFrame */
    public SchoolalzyerFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputFilesLabel = new javax.swing.JLabel();
        selectInputFilesButton = new javax.swing.JButton();
        templateFileLabel = new javax.swing.JLabel();
        selectTemplateButton = new javax.swing.JButton();
        outputFileLabel = new javax.swing.JLabel();
        selectOutputFileButto = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        templateStatusLabel = new javax.swing.JLabel();
        outputStatusLabel = new javax.swing.JLabel();
        inputStatusLabel = new javax.swing.JLabel();
        applyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Schoolalyzer");

        inputFilesLabel.setText("Eingabedateien:");

        selectInputFilesButton.setText("Auswählen");
        selectInputFilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectInputFilesButtonActionPerformed(evt);
            }
        });

        templateFileLabel.setText("Vorlage:");

        selectTemplateButton.setText("Auswählen");
        selectTemplateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTemplateButtonActionPerformed(evt);
            }
        });

        outputFileLabel.setText("Ausgabedatei:");

        selectOutputFileButto.setText("Auswählen");
        selectOutputFileButto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectOutputFileButtoActionPerformed(evt);
            }
        });

        templateStatusLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolalyzer/icons/dialog-information.png"))); // NOI18N
        templateStatusLabel.setText("Bitte Vorlage laden!");

        outputStatusLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolalyzer/icons/dialog-information.png"))); // NOI18N
        outputStatusLabel.setText("Bitte Ausgabedatei auswählen !");

        inputStatusLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolalyzer/icons/dialog-information.png"))); // NOI18N
        inputStatusLabel.setText("Bitte Eingabedateien laden!");

        applyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolalyzer/icons/task-complete.png"))); // NOI18N
        applyButton.setText("Anwenden");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputFilesLabel)
                            .addComponent(templateFileLabel)
                            .addComponent(outputFileLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectOutputFileButto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outputStatusLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectTemplateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(templateStatusLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectInputFilesButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputStatusLabel))))
                    .addComponent(applyButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(templateFileLabel)
                    .addComponent(selectTemplateButton)
                    .addComponent(templateStatusLabel))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputFilesLabel)
                            .addComponent(selectInputFilesButton)
                            .addComponent(inputStatusLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(outputFileLabel)
                            .addComponent(selectOutputFileButto)))
                    .addComponent(outputStatusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(applyButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectInputFilesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectInputFilesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectInputFilesButtonActionPerformed

    private void selectOutputFileButtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectOutputFileButtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectOutputFileButtoActionPerformed

    private void selectTemplateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTemplateButtonActionPerformed
        //Show a dialog
        JFileChooser templateChooser = new JFileChooser();
        templateChooser.setDialogTitle("Select the template");
        templateChooser.setMultiSelectionEnabled(false);
        templateChooser.showOpenDialog(null);
        File templateFile = templateChooser.getSelectedFile();
        //Load the template
        try {
            templateWorkbook = loadWorkbook(templateFile);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Eingabefehler beim Lesen der Vorlage: " + ex.getLocalizedMessage(), "Eingabefehler", JOptionPane.ERROR_MESSAGE, errorIcon);
        } catch (InvalidFormatException ex) {
            JOptionPane.showMessageDialog(this, "Fehler beim Lesen der Vorlage: Das Dateiformat wird nicht unterstützt: " + ex.getLocalizedMessage(), "Format nicht unterstützt", JOptionPane.ERROR_MESSAGE, errorIcon);
        }
    }//GEN-LAST:event_selectTemplateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SchoolalzyerFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JLabel inputFilesLabel;
    private javax.swing.JLabel inputStatusLabel;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel outputFileLabel;
    private javax.swing.JLabel outputStatusLabel;
    private javax.swing.JButton selectInputFilesButton;
    private javax.swing.JButton selectOutputFileButto;
    private javax.swing.JButton selectTemplateButton;
    private javax.swing.JLabel templateFileLabel;
    private javax.swing.JLabel templateStatusLabel;
    // End of variables declaration//GEN-END:variables
}
